### ISSUE TITLE
Could I use it on neovim?

### ISSUE THREAD

**Issue by golovo** [arzg/rustdoc-theme#1]
thanks

**Comment by lunacookies** [comment]
This repo only includes themes for VS Code.

I’d encourage you to port the themes to Vim, though, if you’d like! [Colortemplate](https://github.com/lifepillar/vim-colortemplate) is great for this. Take a look at the JSON files in the [`themes` directory](https://github.com/lunacookies/rustdoc-theme/tree/efa66ed1443dcc60ec5dac356ae705049ccb88fc/themes) – it shouldn’t be too hard to copy-paste the hex color values into a Colortemplate file and assign some appropriate highlight groups.
